env:
  browser: true
  es2020: true
  node: true
extends: [
  'eslint:recommended',
  'plugin:mocha/recommended'
]
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
plugins:
    - mocha
globals:
    __dirname: true
    __filename: true
    after: true
    before: true
    describe: true
    exports: true
    it: true
    process: true
