image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
# The creation of the .env file is just to help facilitate getting up and running quickly, none of these values should be used
# in a production instance
tasks:
  - init: brew install terraform terraform-docs
  - init: pip install pre-commit
  - init: npm install
  - init: pre-commit install
  - init: |
        cat > .env << EOF
        NODE_ENV=development
        PORT=3000
        JWT_KEY=test123
        DATABASE_HOST=localhost
        DATABASE_PORT=5432
        DATABASE_USERNAME=gitpod
        DATABASE_NAME=postgres
        DATABASE_SCHEMA=public
        BYPASS_LOGIN=true
        EOF
