language: node_js
node_js:
- 12
python:
- 3.6
install:
- npm install
- npm install -g codecov
- npm install -g nyc
- pip install mkdocs
services:
- postgresql
- docker
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- npm run db-create
script:
- npm test
after_script:
- nyc --reporter=text-lcov npm test > coverage.lcov
- codecov
before_deploy:
- mkdocs build --verbose --clean --strict
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: site
  target_branch: gh-pages
  on:
    branch: master
notifications:
  slack:
    secure: U4+tEb6IRX5XHNoX/cCBr0jxEbCINpWbhX3D4kHf2YOPEKtdGeZFZh/hqAwXSRRdQIXiEvmrRTD42IEZwWK4HgZ6ZTeLF2C17afg7o0kvxHbVhp+1PS9/BFUx0+5KrYB8Ew4US8f/qq6myCx7gtI9dZImH2m5EpgmTHTumEWkGK5PHJBbwL/0GYsO551eT2QimaBvUvAIe++rB5fK0MveCaT2T1ZmprQTQWLRY2tLXbKyBTpiIgC73lbXWCadO2MbBCx7dFSIJVfFWWa86E7dXBfK1Nk4EClMYaAdnqM+mFLx01NINOrpYuzXt8RQivP9OAitTdDpqwIqJcmn+uE3r48w6Hf9onojZfqbytOMIvybgPlLPOhZGwRFFa9xZWUG4JT6X747t/RcrEQXl8wbbm7QaRKLk60zgLH0ysvUFLr6cl+CCzZqTmRbWgGh5NiNS1U6XrjiQR4GVZkKPwLjx9+1ZgaayPkzaFReOETgc72X1WJClkm108R2lLfqvn9iF4C19EmuQpLehzXFXIDN5kHHvKFhbG4jiZwYwMQH0R1OqYhrwB3QWO1Scco6Z7zUcrN9S0KDu4p46sUoLsrk6+DP8VbHDMpiPt0wPOJnvzSeoqYgSYYMuCITr/VMvz6VS7E65swNHMJEWsz+SDsLUnamhUHanMPJzGrk7zmnBY=
env:
  global:
  - secure: pG4ZWAp2dSds5RXlH5wT38GIqwT/px7ubgpgioJzFqy8Q9trkxDyEk3hlGeEPASpfdNGRveA5w5JbGedWCQhIDs2SIDcQA/dh8WnDtiGz+RTlAuUUvsy91WyjEsmaPc2D/YFRMSXiUi3QDUXUSXt2SUtBl8hSuzcnnZMy6BtU+edPqR6hO53c23roE8V6h14O+YoUkbfdyRQBMi5G/WFZxLCpWVsiVP7X0IjOES/E+RFU4vAddT/Q3HaX+RJwqWReItCyluMsJhbfYSLI8m1QbZ38hseJgF3SIqPrWMCOsPdh0AlugTMKbWIIsJi1ba4LzmFjrh5so4F0OdhGhKItlCQ2bOlSIF5sd4kAni1BIX8u2MIIaghM0TM7r4owFj5u1a5AbRkLHVu2J7p7SlHM2WYjlbcqnyuwJYcahGJnFI1K8SpeV5p90Cp3ovtN+f9913cZhQWSL1kshYsFhJD4yfO1eD2ljplC3ufblHi7YXaSgQQNNwo3Y/B6x2AKTGqIOy0LQaidvIWI/9ZRBWoQheFJMA4ZBEYidR3D2AwR4G467NYxrLbdf/1iyMDmWR/yOQtBHAYZ/TyxAjJgyLrofse6XoznW8oN5ky30GqonI/3nID6LOHCQppk18idPpfmlAzMh0KjdD6U/4SJOsc+k/Z3aF0MwTwHdDSYPuwefM=
  - secure: c2PQ9Lkzj7nb7jfmp8vzWhgxh0ALMD9o8ylcAsIBwKZFA60Y6cGzBPdTLhjb7UlBXg9JjDtUMZMZZJBCwoh13nkszE4DV2/u9EPDrt7/2CTLHY8m23TwxbVhcqjNypE4FXRbmmq6MQBeFmN67PeNfgJtzAOHt5+W7XA68CfpYnyEoLm3Qsm3tkNE9PQ2JCnLBqrAhIF3lyQq1odwjT7ls00wgaTN/V59XanbXQFO5NmpWD33wmq02E9AqsH4WGcbyx4vFyby1ubr0EWgV1UQRUh6R4+KQ6E6LiX6LYCZQhY1f2CiBaueZ1l1nMSF3plbrgp9ya46bXlL7bRSJIiecdw4wkYpz/idX4JuJ6S+fFK27mfq7mGkyjXeN5l/69CQTxqBp2UWnLZCkkS8qypPNUl/87zKWzSbMKnSKdQVQje9MADonkAVfX8ZmJlwRReLZVdt6bnEG1RaJN+dLOycyJETRPuB5yFCghKvoUbLbDFthVJAWRha5ABhRwiAt9+zMU1L+/vlYh8EZ9z+olQsoJxOm0mT7uEky44qH0BN4WXAKj15QvYabxCoMuU/wtLtw+ZKIBApyCS61JG3u3t/Qw/6AaAusoUD8zD8OI4NNoSpO4Z9YT/zccgYA3/f6lJ4W6FnlgnC+IWIKkT2OFnrrmyYgo72457PL/Uh2MZDT1c=
