language: node_js
node_js: 
    - 12

install:
    - npm install
    - npm install -g codecov
    - npm install -g nyc

services:
    - postgresql

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - npm test 
after_script:
    - nyc --reporter=text-lcov npm test > coverage.lcov
    - codecov
