language: node_js
node_js: 
    - 12

install:
    - npm install
    - npm install -g codecov

services:
    - postgresql

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
    - codecov
