version: '3'
services:
  api:
    build: .
    depends_on: 
      - db
    links:
      - "db: database"
    ports:
      - '3000:3000'
    command:  >
      sh -c "npm run db-delete &&
            npm run db-create && 
            npm run db-seed &&
            npm start"
    volumes:
      - .:/app/
      - /app/node_modules
    env_file: .env
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}