version: "3"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    expose:
      - ${PORT:-3001}
    volumes:
      - ./src:/usr/src/src
    command: >
      sh -c "npm run db-delete &&
             npm run db-create &&
             npm run db-seed &&
             npm start"
    environment:
      - PORT=${PORT:-3001}
      - NODE_ENV=${NODE_ENV:-development}
      - BYPASS_LOGIN=${BYPASS_LOGIN:-true}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA:-public}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - JWT_KEY=${JWT_KEY:?JWT_KEY must be set}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?DATABASE_PASSWORD must be set}
  web:
    build:
      context: https://github.com/CodeForBaltimore/Healthcare-Rollcall.git#${WEB_TAG:-master}
    depends_on:
      - api
    ports:
      - ${WEB_PORT:-3000}:${WEB_PORT:-3000}
    expose:
      - ${WEB_PORT:-3000}
    environment:
      - PORT=${WEB_PORT:-3000}
      - VUE_APP_BASE_API_URL=http://localhost:${PORT:-3001}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?DATABASE_PASSWORD must be set}
  db:
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?DATABASE_PASSWORD must be set}
