version: '3'
services:
  api:
    build: .
    depends_on: 
      - db
    ports:
      - '3000:3000'
    command: npm start
  db:
    image: postgres
    restart: always
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data: