version: '3'
services:
  api:
    image: bmoreres
    depends_on: 
      - db
    links:
      - "db: database"
    ports:
      - '3000:3000'
    command: >
      sh -c "npm run db-create && 
             npm start"
    volumes:
      - .:/app/
      - /app/node_modules
    env_file: .env
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}