
service: bmore-responsive
custom:
  region: ${opt:region,'us-east-1'}
  prune:
    automatic: true
    number: 3
  serverless-offline:
    port: ${self:provider.environment.PORT}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    forceInclude:
      - pg
      - pg-native
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:provider.environment.NODE_ENV}
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref": "ServerlessDeploymentBucket"
functions:
  - '${file(./src/lambda/lambda.serverless.yml)}'
plugins:
    - serverless-domain-manager
    - serverless-dotenv-plugin
    - serverless-offline
    - serverless-prune-plugin
    - serverless-stage-manager
    - serverless-webpack
package:
  individually: true
