name: Bmore Responsive CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      DATABASE_PASSWORD: password
      JWT_KEY: fortestsonly
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install npm packages
        run: npm install

      - name: Build docker stack
        run: docker-compose up -d --build

      - name: Lint
        run: npm run lint

      - name: Test
        run: |
          docker exec bmore-responsive-api-1 npm test


